language: python
python:
- 3.6
- 3.5
- 3.4

install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: MridulS
  password:
    secure: iRPz7RVd+KgNvfZaKZ24k+gawfZtnhkMBzqKZUs6PE1cZGfvPHnurksfK9uLYYamyqHAKojJra35JdwcNTKmwfjD+J9FL5/tipI8XZhpTZNV9nqdGdKuP7glRUlok75opJkFrhtgBJ1vf738w91G15+Q3AksVwJ5MhHcstXiZAvVp7RR2AMSGMlkTXybhoYr91EYZ46p3F9TYnJlXfWVj4rCjaX+QhIfQk577iUNOxPHeXYNPkj2vDdSkMiHdgqZdZD56U47U3EapxkETHahn2vGuw4CmMxBx+L4eEOxF6Xb6g3/RKw+Tr1NF4j6pEQQbinguyKaLZeodmMe7pBRutsEPEuDJH1kSB8jEACZ2T01GuHFQtuQr4Sg2DKG6ajXLE3xvBwEJLsoglrH245TvaxLc3BVC89ay0PXysTnv3yk9YxFt7BcH11db/DTNLxhoXrXF3aSHW9wp2E8VLSM9Ofq11thHN9v3JlMjbqmsXRADHxE2r7P+LnMVxgNDklOEYZKBSYbPXaPGVTRfu0o9ELQ+jwC8bQGoHlCtK4b4Wnix22ZZXYlxi8UOwhYAeFmc5GyGoagjYT4MQf3B2VTW6RJhhIFel0es0Q6T/QAU4JvEs1ljPnoPqLJ55c6gHsPS/hWY4YT0tFFf6wGvQwuwzDTp5SfUocbjHwfuB14SHQ=
  on:
    tags: true
    repo: MridulS/pygantt
    python: 3.6
